### PR TITLE
Closes #409 updated scorres to scstresc

### LINKED ISSUE #409: Update SCORRES to SCSTRESC in Eligibility Criteria Checks
The following checks in the codebase need to be updated to replace references to SCORRES with SCSTRESC:

Checks to Update:

- check_sc_dm_eligcrit
- check_sc_dm_seyeselc

Please ensure that all instances of SCORRES within these checks are updated to SCSTRESC and verify the changes to ensure proper functionality.

### PR DESCRIPTION
**Pull request by vbshuliar**
### **Summary:**
This PR updates the checks check_sc_dm_eligcrit and check_sc_dm_seyeselc to replace all references of SCORRES with SCSTRESC as per the new requirements.

### **Changes:**

Updated references of SCORRES to SCSTRESC in the following checks:

- check_sc_dm_eligcrit
- check_sc_dm_seyeselc

### **Testing:**

Verified that the updated checks function correctly with SCSTRESC.

### CODE REVIEW

**Comment by barnett11** [comment]
Hi @vbshuliar - we should also update the tests within https://github.com/pharmaverse/sdtmchecks/tree/devel/tests/testthat

**Comment by vbshuliar** [comment]
Hi reviewers,
I updated the tests as well. I'm not sure if everything looks how you expected, so I am more than happy to make changes according to your recommendations.

**Comment by barnett11** [comment]
Hi @vbshuliar - you may notice that there is a check failing for R CMD Check - this is identifying we've not updated a global variable for `SCSTRESC`. Please update `R/globals.R` for this

**Comment by vbshuliar** [comment]
> Hi @vbshuliar - you may notice that there is a check failing for R CMD Check - this is identifying we've not updated a global variable for `SCSTRESC`. Please update `R/globals.R` for this

Hi @barnett11 !
I've just done it.

**Review by barnett11 — CHANGES_REQUESTED** [review]
Thanks @vbshuliar , some suggested updates thank you,
- `check_sc_dm_seyeselc` description suggests `OU` should be an option, but actually it is not - please update description
- Please also make same update of `SCORRES` to `SCSTRESC` for checks `check_ec_sc_lat` and `check_oe_sc_lat_count_fingers`

Thanks

**Comment by vbshuliar** [comment]
Hi @barnett11 
Please check it now. I am happy to update anything else if needed.

**Review by barnett11 — APPROVED** [review]
All looking good thank you @vbshuliar !

**Comment by barnett11** [comment]
@harriscw - would you like to review before we merge to `devel`?

**Pull request merged**
